### ISSUE TITLE
Add reverse proxy documentation to the website

### ISSUE THREAD

**Issue by kingwarrick** [mail-in-a-box/mailinabox.email#72]
Over the years, a number of users, including myself, have asked for clarification about reverse proxy setup. Some information is found in discourse.miab, but the most substantive is on [github](https://github.com/mail-in-a-box/mailinabox/issues/608#issuecomment-279204357)

I think a third section in the advanced tips/configuration on the website might be helpful, based on the above linked comment.

**Comment by kingwarrick** [comment]
not knowing how to use github, I just pushed something before I was ready. sorry for the admin overhead. I need to add info about regeneration from the github comment:

The configuration must be regenerated/reloaded before this takes effect. You can do so by navigating to Web within the admin panel and clicking on any of the Change buttons or simply run sudo ~/mailinabox/tools/web_update.

**Comment by JoshData** [comment]
Hi @kingwarrick. You actually didn't open a pull request, so I never saw your changes.

**Comment by kingwarrick** [comment]
I think I got it!

**Comment by infidelus** [comment]
Still can't get this to work.  Clearly I'm thick, but I've tried pretty much every variation on the topic @kingwarrick has linked to and nothing seems to work.  While I know they're used a lot in programming, I think the foo bar baz is just confusing me.  I need a real world example if I'm ever going to get my other internal servers talking to the outside world without using non-standard ports.
